### ISSUE TITLE
`symbol` for `name` in `SubroutineCall` ?

### ISSUE THREAD

**Issue by rebcabin** [rebcabin/masr#31]
ASDL says

```c
    | SubroutineCall(symbol name, symbol? original_name, call_arg* args, expr? dt)
```

`name` is a `symbol` instead of the expected `identifier`. `symbol` is a huge type with many heads. Can you give an example of a `name` that is not an `identifier`? Can we refine the type of `name` a little more precisely, i.e., say what heads of `symbol` are allowed? Can you reveal some of the secret metasymantics now implemented in C++?

Ditto for `original_name`.

**Comment by certik** [comment]
It can't be an identifier, because we need there to be a pointer directly to the function, for performance. The backend should never deal with strings, these things need to be figured out.

Relevant documentation:

* https://docs.lfortran.org/en/asr/asr_nodes/expression_nodes/Var/
* https://docs.lfortran.org/en/asr/asr_nodes/symbol_nodes/Variable/

The `name` can point to `Function` (that is the most common case), and I think it can also point to a `Variable` which is of type `FunctionType`, which is used in callbacks (function pointer).

The `original_name` contains the overloaded name, such as "sin", while `name` would contain `sin_f32`, one of the available overload.

**Comment by rebcabin** [comment]
This looks like another ambiguity between an object and a pointer to an object, similar to the ambiguity between a symbol_table's being an actual table sometimes and a symtab_id sometimes. The ASDL types are too loose. I will tighten this up in MASR, but maintain legacy compatibility with `--show-asr`.

**Comment by rebcabin** [comment]
I take it that the tightest type for would also be a `symbol-ref` rather than a string.

**Comment by certik** [comment]
Yes, it's a `symbol-ref`. Represented by just a pointer in C++, but in `--show-asr` you represented by a SymbolTable ID and a name/identifier.

**Comment by rebcabin** [comment]
I've implemented enough for my current examples, with have a naked `symtab-id` and `identifier` for `symbol name` in the legacy sugar. I am not sure of an example fo `symbol? original_name` because my current example has `()` for it. Do you have an example of a non-empty `original_name`? The following tests are checked in pending more examples.

```clojure
(deftest SubroutineCall-test

  (is (s/valid? ::asr/SubroutineCall
                (SubroutineCall--
                 ['test_fn1 7]
                 ()
                 []
                 ()
                 )))
  (is (s/valid? ::asr/SubroutineCall
                (SubroutineCall
                 7
                 test_fn1
                 ()
                 []
                 ()))))
```

**Comment by rebcabin** [comment]
I see this:

```c
-- SubroutineCall/FunctionCall store the actual final resolved subroutine or
-- function (`name` member). They also store the original symbol
-- (`original_name`), which can be one of: null, GenericProcedure or
-- ExternalSymbol.
```

**Comment by rebcabin** [comment]
Found this: looks like `original_name` is either `()` or a naked pair `7 _lpython_main_program`. I'll fix this for legacy, but it's bad practice. The type of `()` is `list`, but a naked pair has no single type. It has two types, `symtab_id` and `identifier`. I can fix for legacy with an ugly macro, which sould eventually go away like all legacies.

```clojure
(ExternalSymbol
 5
 _lpython_main_program
 7 _lpython_main_program
 _global_symbols
 []
 _lpython_main_program
 Public
 )
```
