### ISSUE TITLE
`WhileLoop` doesn't conform to ASDL

### ISSUE THREAD

**Issue by rebcabin** [rebcabin/masr#33]
Example from `asr-expr1-dde511e.stdout` has three parameters:

```clojure
(WhileLoop
                                        () ;; one
                                        (NamedExpr
                                            (Var 2 a)
                                            (IntegerConstant 1 (Integer 4 []))
                                            (Integer 4 [])
                                        ) ;; two
                                        [(=
                                            (Var 2 y)
                                            (IntegerConstant 1 (Integer 4 []))
                                            ()
                                        )] ;; three
                                    )
```

but ASDL from `ASDL_2023_APR_06_snapshot.asdl` specifies only two:

```c
    | WhileLoop(expr test, stmt* body)
```

The first argument in the Example is mysterious. I'll work around it for now.

**Comment by certik** [comment]
The current ASR definition is `WhileLoop(identifier? name, expr test, stmt* body)`, the first argument is probably a "goto target" to jump to, this is needed if you have multiple nested loops and you are doing "break name" to a specific parent loop. There might be a better way to do it, but for now we use this mechanism. Python doesn't allow breaking to a parent loop, but Fortran does.

**Comment by rebcabin** [comment]
ok, that's neat! goto doesn't deserve its bad reputation!

Should the goto target perhaps be a symbol-ref? Or do we want a nice,
refined type for goto-targets? or even labels, generically? What about
computed gotos, where all the labels are numerical? perhaps the labels
ought to be (s/or :numerical ::nat, :symbolic ::symbol-ref)?

**Comment by rebcabin** [comment]
many many times in intense numerical code i wanted to jump to a parent
loop. "Structured Programming" without gotos forces truly pornographic
contortions. Goto is exactly the right answer. Ditto finite-state automata.
Absolutely the fastest FSA's use gotos, not switch stmts, which have extra
jumps to the jump table!

Avoiding gotos is like avoiding mutation: sometimes it's just the wrong
thing to do. Fundamentalist Structured Programming is like Fundamentalist
Declarative Programming. Ever seen real-world Prolog with "cut" and "fail?"
Fundamentalism is too rigid for the real world.

ok this whole issue was settled in the 1980's. I'm just reminding myself of
some engineering taste and judgment principles.

**Comment by rebcabin** [comment]
reopening as documentation reminder as requested by @certik
